version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.4
    ports:
      - "27017:27017"
